# Generated by Django 4.0.4 on 2022-05-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkaro.category')),
            ],
        ),
    ]
